apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: nova-store
  labels:
    app: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: client
          image: novastoreacr.azurecr.io/nova/client:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5173
          livenessProbe:
            tcpSocket:
              port: 5173
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 5173
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: nova-store
spec:
  selector:
    app: client
  ports:
    - port: 5173
      targetPort: 5173
